#!/bin/bash

for i in "$@"; do
	arg+=("$i")
	lastArg=$i
done

helps () {
	printf "\nUsage:\n\n"
	printf "help\n"
	printf "\nExamples:\n\n"
	echo "$0 row 1 text.txt				# delete line 1"
	echo "$0 row \$ text.txt				# delete last line"
	echo "$0 row 1,5 text.txt				# delete a range of lines"
	echo "$0 row 2,4! text.txt				# delete all lines except 2 to 4"
	echo "$0 row newline text.txt 				# delete empty lines"
	echo "$0 row except 1,3 \"hello world\" text.txt	# delete line 1 to 3 except \"hello world\" within line 1 to 3"
	echo
	echo "$0 preffix row 1,2 \"- \" test			# delete hyphen/dash at the beginning of line 1 and 2"
	echo "$0 suffix row 3,4 \";\" test			# delete semi-colon at the end of line 1 and 2"
	echo
	exit 2
}

if [[ ${arg[0]} == "row" || ${arg[0]} == "rownum" ]]; then
	if [[ ${arg[1]} == "" || ${arg[1]} == "-h" || ${arg[1]} == "--help" ]]; then
		helps
	elif [[ ${arg[1]} == "newline" ]]; then
		sed /^$/d $lastArg
		sed -i /^$/d $lastArg
	elif [[ ${arg[1]} == "except" ]]; then
		sed -e ${arg[2]}'s/.*/'${arg[3]}'/' $lastArg
		sed -i ${arg[2]}'s/.*/'${arg[3]}'/' $lastArg
	else
		sed ''${arg[1]}'d' $lastArg
		sed -i ''${arg[1]}'d' $lastArg
	fi
elif [[ ${arg[0]} == "preffix" ]]; then # affix to the left
	if [[ ${arg[1]} == "" || ${arg[1]} == "-h" || ${arg[1]} == "--help" ]]; then
		helps
	elif [[ ${arg[1]} == "row" || ${arg[0]} == "rownum" ]]; then
		sed -e ${arg[2]}'s/'${arg[3]}'*//' $lastArg
		sed -i ${arg[2]}'s/'${arg[3]}'*//' $lastArg
	elif [[ ${arg[1]} == "all" ]]; then
		sed -ne 's/'${arg[2]}'*//p' $lastArg
		sed -i 's/'${arg[2]}'*//' $lastArg
	elif [[ ${arg[1]} == "pattern" ]]; then
		sed -e 's/'${arg[2]}'*//' $lastArg
		sed -i 's/'${arg[2]}'*//' $lastArg
	fi
elif [[ ${arg[0]} == "suffix" ]]; then # affix to the right
	if [[ ${arg[1]} == "" || ${arg[1]} == "-h" || ${arg[1]} == "--help" ]]; then
		helps
	elif [[ ${arg[1]} == "row" || ${arg[0]} == "rownum" ]]; then
		sed -e ${arg[2]}'s/\'${arg[3]}'$//' $lastArg
		sed -i ${arg[2]}'s/\'${arg[3]}'$//' $lastArg
	elif [[ ${arg[1]} == "all" ]]; then
		sed -ne 's/\'${arg[2]}'$//p' $lastArg
		sed -i 's/\'${arg[2]}'$//' $lastArg
	elif [[ ${arg[1]} == "pattern" ]]; then
		sed -e 's/\'${arg[2]}'$//' $lastArg
		sed -i 's/\'${arg[2]}'$//' $lastArg
	fi
else
	helps
fi

exit 0
